//! The reference encoder must BE the reference, not merely resemble it.
//!
//! These run only under `--features reference-encoder`, where a real
//! llama.cpp is linked.

use super::super::kquant::{COMPILABLE, Q6_K};
use super::*;
use serde::Deserialize;

#[derive(Deserialize)]
struct Golden {
    input_bits: Vec<u32>,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    encoding: String,
    elements: usize,
    quantised_hex: String,
}

fn golden() -> Golden {
    serde_json::from_str(include_str!("fixtures/ggml_kquant_golden.json"))
        .expect("the ggml golden fixture parses")
}

fn input() -> Vec<f32> {
    golden()
        .input_bits
        .iter()
        .copied()
        .map(f32::from_bits)
        .collect()
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len() / 2)
        .map(|i| u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).expect("hex"))
        .collect()
}

/// **The closed loop.** The fixture was generated by calling
/// `ggml_quantize_chunk` with one row of 512; this calls the same
/// function through the FFI with the same geometry, so the bytes must be
/// identical — not close, identical.
///
/// A mismatch means the FFI is mis-wired (wrong type id, wrong row
/// geometry, wrong argument order), and every one of those would
/// otherwise surface as a mysteriously poor arm in a campaign.
#[test]
fn the_reference_encoder_reproduces_the_golden_bytes_exactly() {
    let src = input();
    for c in &golden().cases {
        let k = COMPILABLE
            .into_iter()
            .find(|k| k.name.eq_ignore_ascii_case(&c.encoding))
            .expect("fixture encoding is compilable");
        let theirs = hex_to_bytes(&c.quantised_hex);
        let mine = encode(k, &src[..c.elements], c.elements, "golden").expect("encodes");
        assert_eq!(
            mine, theirs,
            "{}: the linked ggml did not reproduce the fixture's own bytes",
            k.name
        );
    }
}

/// Row framing must be VALID, but for a block-aligned tensor it does not
/// change the bytes — and an earlier version of this test wrongly
/// asserted that it does.
///
/// The mistake is worth recording so it is not re-added: a K-quant row
/// is an independent sequence of super-blocks, so `[1, 512]` and
/// `[2, 256]` at Q6_K frame the *same* 256-value windows in the same
/// order and encode identically. Row framing decides **whether a tensor
/// can be encoded at all**, not what the bytes are once it can. The
/// bytes-differ premise was false, and the assertion failed on correct
/// code.
///
/// What is real, and asserted here: a row length that is not a whole
/// number of blocks is refused rather than silently reframed.
#[test]
fn a_row_that_is_not_a_whole_number_of_blocks_is_refused() {
    let src = input();
    // 128 divides 512 evenly, so the values DO split into rows — the
    // refusal must come from the block geometry, not from the split.
    let err = encode(Q6_K, &src[..512], 128, "some.tensor")
        .unwrap_err()
        .to_string();
    assert!(err.contains("some.tensor"), "{err}");
    assert!(
        err.contains("128") && err.contains("256"),
        "the refusal must name the row length and the block size: {err}"
    );
}

/// The block-aligned reframing that legitimately produces identical
/// bytes — pinned so the refusal above is not mistaken for "any
/// reframing is rejected".
#[test]
fn block_aligned_reframings_agree_because_the_windows_are_the_same() {
    let src = input();
    let one_row = encode(Q6_K, &src[..512], 512, "t").expect("encodes");
    let two_rows = encode(Q6_K, &src[..512], 256, "t").expect("encodes");
    assert_eq!(one_row, two_rows);
}

#[test]
fn a_value_count_that_does_not_divide_into_rows_is_refused() {
    let src = input();
    let err = encode(Q6_K, &src[..512], 300, "some.tensor")
        .unwrap_err()
        .to_string();
    assert!(err.contains("some.tensor"), "{err}");
    assert!(err.contains("rows of 300"), "{err}");
}

/// A comparative artifact whose provenance says `unpinned` is still a
/// valid artifact, but it is not a reproducible comparison — so the
/// value must reach the record rather than being defaulted silently.
#[test]
fn the_pinned_upstream_is_recorded_one_way_or_the_other() {
    assert!(!PINNED_UPSTREAM.is_empty());
}
