//! SiTU-GLU parity against the committed oracle (K3-ACT-1).
//!
//! The fixture is generated by `scripts/situ_oracle_export.py` from
//! `scripts/situ_reference.py`, itself a verbatim transcription of
//! Kimi-K3's own `SituAndMul.forward` (`modeling_kimi_linear.py` L64-91).
//! Committed rather than generated at test time: a fixture that needs
//! torch is a test that is absent wherever torch is.
//!
//! Two ARMS, both legitimate configurations of the reference and neither
//! a control of the other — K3's `(beta 4.0, linear_beta 25.0)` and the
//! reference's own `linear_beta = None` form.
//!
//! # What the controls are for
//!
//! Each arm carries seven named defects with their MEASURED deltas. They
//! are not alternative implementations to test; they are the proof that
//! this test could fail. The first of them, `swiglu`, is the defect this
//! rung removes: it is precisely what
//! `Activation::from_hf_name("situ") -> None -> unwrap_or(Silu)` computed
//! before K3-ACT-1, and at K3's parameters it reads rel-L2 7.37 — so a
//! build that regressed to it could not pass the parity assertion above.

use larql_models::{Activation, ExpertGatePolicy};
use ndarray::Array2;

use crate::ffn::expert_weight::gate;
use crate::MoeGateRule;

const ORACLE: &str = include_str!("situ_oracle.json");

/// Parity tolerance. The reference computes in f64-backed torch f32 and
/// this side in Rust f32 over the identical expression, so the only
/// admissible difference is the last-ulp disagreement of `tanh`/`exp`
/// between the two libms.
const TOLERANCE: f32 = 1e-5;

/// Every control must be at least this discriminable for the arm's parity
/// assertion to mean anything. Set well below the smallest control that
/// is expected to be non-zero (`bf16_throughout`, 2.2e-3) and well above
/// `TOLERANCE`, so it is a floor on SENSITIVITY and not a restatement of
/// the tolerance.
const CONTROL_FLOOR: f64 = 1e-3;

fn oracle() -> serde_json::Value {
    serde_json::from_str(ORACLE).expect("situ_oracle.json parses")
}

fn floats(v: &serde_json::Value, key: &str) -> Vec<f32> {
    v[key]
        .as_array()
        .unwrap_or_else(|| panic!("`{key}` is an array"))
        .iter()
        .map(|x| x.as_f64().expect("a number") as f32)
        .collect()
}

fn rule_of(arm: &serde_json::Value) -> MoeGateRule {
    MoeGateRule::SituGlu {
        beta: arm["beta"].as_f64().expect("beta") as f32,
        linear_beta: arm["linear_beta"].as_f64().map(|v| v as f32),
    }
}

/// The scalar authority reproduces the reference on every exported point,
/// on both arms.
///
/// Point-by-point rather than aggregated: SiTU is exactly zero wherever
/// the gate is zero, and a norm over the whole grid would let a defect
/// concentrated on those points hide inside the scale of the rest.
#[test]
fn the_scalar_combine_reproduces_the_reference_on_both_arms() {
    let fixture = oracle();
    for (name, arm) in fixture["arms"].as_object().expect("arms").iter() {
        let (gate, up, want) = (floats(arm, "gate"), floats(arm, "up"), floats(arm, "out"));
        let rule = rule_of(arm);
        assert!(!gate.is_empty(), "arm {name} exported no points");
        for (i, ((&g, &u), &expected)) in gate.iter().zip(up.iter()).zip(want.iter()).enumerate() {
            let got = rule.combine(g, u);
            assert!(
                (got - expected).abs() <= TOLERANCE * expected.abs().max(1.0),
                "arm {name} point {i}: gate {g}, up {u} — got {got}, reference says {expected}"
            );
        }
    }
}

/// The `Array2` tier agrees with the scalar authority exactly.
///
/// Exactly, not approximately: `gate::apply` is documented as only
/// SHAPING `MoeGateRule::combine` over a matrix. Any difference at all
/// means a second transcription of the formula has appeared, which is the
/// arrangement this crate refuses everywhere else.
#[test]
fn the_array_tier_delegates_to_the_scalar_authority_bit_for_bit() {
    let fixture = oracle();
    for (name, arm) in fixture["arms"].as_object().expect("arms").iter() {
        let (gate, up) = (floats(arm, "gate"), floats(arm, "up"));
        let n = gate.len();
        let g2 = Array2::from_shape_vec((1, n), gate.clone()).expect("row");
        let u2 = Array2::from_shape_vec((1, n), up.clone()).expect("row");

        let policy = ExpertGatePolicy::SituGlu {
            beta: arm["beta"].as_f64().expect("beta") as f32,
            linear_beta: arm["linear_beta"].as_f64().map(|v| v as f32),
        };
        // The `Activation` argument is inert under a non-plain policy;
        // `situ_policy_makes_the_activation_field_inert` proves it rather
        // than this test assuming it.
        let shaped = gate::apply(&g2, &u2, policy, Activation::Silu);
        let rule = rule_of(arm);
        for (i, (&s, (&g, &u))) in shaped.iter().zip(gate.iter().zip(up.iter())).enumerate() {
            assert_eq!(
                s,
                rule.combine(g, u),
                "arm {name} point {i}: the Array2 tier and the scalar rule disagree"
            );
        }
    }
}

/// The activation carried beside a SiTU policy changes nothing.
///
/// The surface stores an `Activation` for every FFN, and under a
/// non-plain gate policy no executor reads it. That is a claim about
/// `MoeGateRule::from_arch`'s match, and this is the witness: run the
/// whole grid under `Silu` and under `GeluTanh` and require bit
/// identity. Without it, a future refactor could start consulting the
/// field under SiTU and nothing would notice.
#[test]
fn situ_policy_makes_the_activation_field_inert() {
    let fixture = oracle();
    for (name, arm) in fixture["arms"].as_object().expect("arms").iter() {
        let (gate, up) = (floats(arm, "gate"), floats(arm, "up"));
        let policy = ExpertGatePolicy::SituGlu {
            beta: arm["beta"].as_f64().expect("beta") as f32,
            linear_beta: arm["linear_beta"].as_f64().map(|v| v as f32),
        };
        let silu = MoeGateRule::from_arch(policy, Activation::Silu);
        let gelu = MoeGateRule::from_arch(policy, Activation::GeluTanh);
        for (&g, &u) in gate.iter().zip(up.iter()) {
            assert_eq!(
                silu.combine(g, u),
                gelu.combine(g, u),
                "arm {name}: the activation beside a SiTU policy is being read"
            );
        }
    }
}

/// Every control is discriminable, and the one that reads zero is proved
/// able to read otherwise.
///
/// `up_cap_omitted` is exactly 0.0 on the `no_linear_cap` arm — correctly,
/// since that arm HAS no up cap to omit. A control reading zero is only
/// admissible when the same control reads non-zero somewhere, otherwise
/// it is a blind instrument dressed as a passing check
/// (`feedback_saturated_softmax_blinds_an_oracle`,
/// `feedback_verification_needs_verification`).
#[test]
fn every_control_could_have_failed_this_test() {
    let fixture = oracle();
    let arms = fixture["arms"].as_object().expect("arms");
    let mut structurally_inert: Vec<(&str, &str)> = Vec::new();

    for (arm_name, arm) in arms.iter() {
        let controls = arm["controls"].as_object().expect("controls");
        assert!(!controls.is_empty(), "arm {arm_name} exported no controls");
        for (control, measured) in controls.iter() {
            let delta = measured["rel_l2"].as_f64().expect("rel_l2");
            if delta == 0.0 {
                structurally_inert.push((arm_name.as_str(), control.as_str()));
                continue;
            }
            assert!(
                delta >= CONTROL_FLOOR,
                "arm {arm_name} control {control} reads {delta}, below the {CONTROL_FLOOR} \
                 sensitivity floor — the fixture cannot tell that defect from the reference"
            );
        }
    }

    for (arm_name, control) in structurally_inert {
        let elsewhere = arms.iter().any(|(other, arm)| {
            other != arm_name
                && arm["controls"][control]["rel_l2"]
                    .as_f64()
                    .is_some_and(|d| d >= CONTROL_FLOOR)
        });
        assert!(
            elsewhere,
            "control {control} reads 0.0 on arm {arm_name} and on every other arm — it proves \
             nothing anywhere and must not be counted as a control"
        );
    }
}

/// The substitution this rung removes is large enough that regressing to
/// it would fail the parity test above.
///
/// Stated as its own assertion rather than left implicit in the control
/// sweep: `swiglu` is not one control among seven, it is THE defect
/// (`hidden_act: "situ"` silently resolving to SiLU), and the rung's whole
/// claim rests on it being consequential at K3's declared parameters.
#[test]
fn the_swiglu_substitution_is_the_large_defect_this_rung_removes() {
    let fixture = oracle();
    let k3 = &fixture["arms"]["k3"];
    let delta = k3["controls"]["swiglu"]["rel_l2"]
        .as_f64()
        .expect("the swiglu control");
    assert!(
        delta > 1.0,
        "SwiGLU reads only rel-L2 {delta} against SiTU at K3's parameters (beta {}, \
         linear_beta {}) — if the substitution were this benign the rung would be arguing \
         about nothing",
        k3["beta"],
        k3["linear_beta"],
    );
}

/// `beta or 1.0` — the reference's Python truthiness — resolved from real
/// configs, against the fixture's own table.
///
/// The cases are read from the oracle rather than restated here, so the
/// rule has exactly one home. The trap is `activation_situ_beta: 0.0`:
/// read literally it divides by zero, and the reference resolves it to
/// 1.0 because `0.0 or 1.0` is `1.0`.
#[test]
fn the_declared_betas_resolve_the_way_the_reference_resolves_them() {
    let fixture = oracle();
    let cases = fixture["parameter_resolution"]
        .as_array()
        .expect("parameter_resolution");
    assert!(!cases.is_empty(), "the oracle exported no resolution cases");

    for case in cases {
        let mut config = serde_json::json!({
            "model_type": "kimi_linear",
            "hidden_size": 8,
            "num_hidden_layers": 1,
            "hidden_act": "situ",
        });
        for (key, value) in [
            ("activation_situ_beta", &case["declared_beta"]),
            ("activation_situ_linear_beta", &case["declared_linear_beta"]),
        ] {
            if !value.is_null() {
                config[key] = value.clone();
            }
        }

        let arch = larql_models::detect_from_json(&config);
        let want_beta = case["resolved_beta"].as_f64().expect("resolved_beta") as f32;
        let want_linear = case["resolved_linear_beta"].as_f64().map(|v| v as f32);
        match arch.expert_gate_policy() {
            ExpertGatePolicy::SituGlu { beta, linear_beta } => {
                assert_eq!(
                    (beta, linear_beta),
                    (want_beta, want_linear),
                    "declared beta {:?} / linear_beta {:?} resolved to ({beta}, {linear_beta:?})",
                    case["declared_beta"],
                    case["declared_linear_beta"],
                );
            }
            other => panic!("`hidden_act: \"situ\"` resolved to {other:?}, not a SiTU policy"),
        }
    }
}

/// A checkpoint that declares the betas without declaring `situ` does not
/// get a SiTU FFN.
///
/// The parameters do not name the operator — that is the whole distinction
/// `expert_gate_policy`'s comment draws between reading a NAME and
/// inferring an operator from an adjacent value, and it is the same
/// mistake `swiglu_limit` is deliberately not allowed to make.
#[test]
fn the_beta_keys_alone_do_not_summon_a_situ_policy() {
    let arch = larql_models::detect_from_json(&serde_json::json!({
        "model_type": "llama",
        "hidden_size": 8,
        "num_hidden_layers": 1,
        "hidden_act": "silu",
        "activation_situ_beta": 4.0,
        "activation_situ_linear_beta": 25.0,
    }));
    assert_eq!(arch.expert_gate_policy(), ExpertGatePolicy::Gated);
    assert_eq!(arch.activation(), Activation::Silu);
}
