#[cfg(feature = "research")]
pub mod attention_capture_cmd;
#[cfg(feature = "research")]
pub mod attention_walk_cmd;
#[cfg(feature = "research")]
pub mod attn_bottleneck_cmd;
#[cfg(feature = "research")]
pub mod bfs_cmd;
#[cfg(feature = "research")]
pub mod bottleneck_test_cmd;
pub mod build_cmd;
#[cfg(feature = "research")]
pub mod circuit_discover_cmd;
pub mod compile_cmd;
pub mod convert_cmd;
#[cfg(feature = "research")]
pub mod embedding_jump_cmd;
pub mod extract_index_cmd;
#[cfg(feature = "research")]
pub mod ffn_bottleneck_cmd;
#[cfg(feature = "research")]
pub mod ffn_latency_cmd;
#[cfg(feature = "research")]
pub mod ffn_overlap_cmd;
#[cfg(feature = "research")]
pub mod fingerprint_extract_cmd;
pub mod hf_cmd;
#[cfg(feature = "research")]
pub mod index_gates_cmd;
#[cfg(feature = "research")]
pub mod kg_bench_cmd;
#[cfg(feature = "research")]
pub mod ov_gate_cmd;
#[cfg(feature = "research")]
pub mod predict_cmd;
#[cfg(feature = "research")]
pub mod projection_test_cmd;
#[cfg(feature = "research")]
pub mod qk_modes_cmd;
#[cfg(feature = "research")]
pub mod qk_rank_cmd;
#[cfg(feature = "research")]
pub mod qk_templates_cmd;
#[cfg(feature = "research")]
pub mod residuals_cmd;
#[cfg(feature = "research")]
pub mod trajectory_trace_cmd;
#[cfg(feature = "research")]
pub mod vector_extract_cmd;
pub mod verify_cmd;
pub mod walk_cmd;
// pub mod vindex_bench_cmd;  // Removed: uses deprecated DownClusteredFfn
#[cfg(feature = "research")]
pub mod weight_walk_cmd;
