//! The five hyper-connection stages, each judged on its own (wave 17).
//!
//! `hyper_connection_oracle.json` is generated by
//! `scripts/hyper_connection_oracle_export.py`, a torch transcription of
//! DeepSeek-V4-Flash's own `inference/kernel.py` and `inference/model.py`.
//! The Rust side reads the same two reference files independently and
//! shares no arithmetic with the generator.
//!
//! **Every stage is asserted separately.** Wave 16 named the Sinkhorn
//! split as its own operation precisely so that this file could exist:
//! a hyper-connected sublayer that is only checked end to end can be
//! wrong in the split and right in the sum, and the composed output
//! would still look plausible.
//!
//! **The controls are the load-bearing part.** Each one is a
//! deliberately wrong variant, and each must disagree with the reference
//! by more than [`TOLERANCE`]. A fixture on which the transposed
//! combination matrix agreed would be a fixture that cannot see index
//! order — the assertion would pass and prove nothing. The fixture is
//! shaped for that: four streams built at scales spanning 70x, whose
//! realised L2 norms end up 28x to 76x apart depending on position; a
//! hidden width of five that is neither a power of two nor the stream
//! count; and three positions that are not scalar multiples of each
//! other.

use serde_json::Value;

use crate::format::vindex3::opplan::exec::hyper_connection::{
    expand_embedding, expand_streams, head_reduce, mix_projection, mix_rows_for, reduce_streams,
    split_sinkhorn, sublayer_forward, HeadWeights, SiteWeights, HC_SCALE_LEN,
};
use larql_models::config::HyperConnection;

const ORACLE: &str = include_str!("hyper_connection_oracle.json");

/// f32 transcription noise between two implementations of the same
/// arithmetic in different orders. The generator accumulates in torch's
/// vectorised f32; this side accumulates in plain scalar loops, so sums
/// over `streams * hidden = 20` terms differ in the last places. The
/// largest fixture values are around 20, so this is roughly 1e-6
/// relative — and every control below moves things by 1e-3 or more,
/// three of them by 0.1 or more.
const TOLERANCE: f32 = 5e-5;

/// The smallest disagreement a control must produce to count as one. Set
/// well above [`TOLERANCE`] so "the control differs" cannot be satisfied
/// by transcription noise.
const CONTROL_FLOOR: f32 = 1e-4;

struct Oracle {
    doc: Value,
}

impl Oracle {
    fn load() -> Self {
        Self {
            doc: serde_json::from_str(ORACLE).expect("oracle json parses"),
        }
    }

    fn usize_at(&self, key: &str) -> usize {
        self.doc[key].as_u64().expect("integer field") as usize
    }

    fn f64_at(&self, key: &str) -> f64 {
        self.doc[key].as_f64().expect("float field")
    }

    fn floats(&self, path: &[&str]) -> Vec<f32> {
        let mut node = &self.doc;
        for step in path {
            node = &node[step];
        }
        node.as_array()
            .unwrap_or_else(|| panic!("{path:?} is an array"))
            .iter()
            .map(|v| v.as_f64().expect("float element") as f32)
            .collect()
    }

    fn topology(&self) -> HyperConnection {
        HyperConnection {
            streams: self.usize_at("streams"),
            sinkhorn_iters: self.usize_at("sinkhorn_iters"),
            sinkhorn_eps: self.f64_at("hc_eps"),
        }
    }
}

/// One position's slice out of a `[positions, ..]` flat array.
fn chunk(all: &[f32], position: usize, width: usize) -> &[f32] {
    &all[position * width..(position + 1) * width]
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "comparing different shapes");
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn assert_close(actual: &[f32], expected: &[f32], what: &str) {
    let diff = max_abs_diff(actual, expected);
    assert!(
        diff <= TOLERANCE,
        "{what}: max |diff| {diff:e} exceeds {TOLERANCE:e}"
    );
}

/// The branch the generator uses for stage four: `tanh(W @ v)`. A plain
/// map is enough — the stage's claim is that it sees `[hidden]` and not
/// `[streams, hidden]`, not what it computes.
fn branch(v: &[f32], weight: &[f32], hidden: usize) -> Vec<f32> {
    let mut out = vec![0.0f32; hidden];
    for (o, row) in out.iter_mut().zip(weight.chunks_exact(hidden)) {
        *o = row.iter().zip(v).map(|(w, x)| w * x).sum::<f32>().tanh();
    }
    out
}

#[test]
fn stage_1_the_mix_projection_matches_the_reference() {
    let o = Oracle::load();
    let (streams, hidden, positions) = (
        o.usize_at("streams"),
        o.usize_at("hidden"),
        o.usize_at("positions"),
    );
    let mix_rows = o.usize_at("mix_rows");
    let (x, hc_fn) = (o.floats(&["input", "x"]), o.floats(&["weights", "hc_fn"]));
    let expected = o.floats(&["stages", "mix_projection"]);
    let norm_eps = o.f64_at("norm_eps");

    for p in 0..positions {
        let got = mix_projection(
            chunk(&x, p, streams * hidden),
            streams,
            hidden,
            &hc_fn,
            mix_rows,
            norm_eps,
        );
        assert_close(&got, chunk(&expected, p, mix_rows), "mix projection");
    }
}

/// The RMS epsilon is the component's `norm_eps`, not the topology's
/// `sinkhorn_eps`. They are equal in DeepSeek-V4-Flash by coincidence,
/// so this asserts against a deliberately different value rather than
/// against `hc_eps` itself — otherwise the test could not fail.
#[test]
fn stage_1_uses_the_components_norm_eps_and_not_the_topologys() {
    let o = Oracle::load();
    let (streams, hidden) = (o.usize_at("streams"), o.usize_at("hidden"));
    let mix_rows = o.usize_at("mix_rows");
    let (x, hc_fn) = (o.floats(&["input", "x"]), o.floats(&["weights", "hc_fn"]));
    let wrong = o.floats(&["controls", "mix_projection_wrong_eps"]);
    let right = o.floats(&["stages", "mix_projection"]);

    assert!(
        max_abs_diff(&wrong, &right) > CONTROL_FLOOR,
        "the control epsilon must actually change the projection, else this test is vacuous"
    );

    let first = chunk(&x, 0, streams * hidden);
    let got = mix_projection(first, streams, hidden, &hc_fn, mix_rows, 1e-3);
    assert_close(
        &got,
        chunk(&wrong, 0, mix_rows),
        "mix projection at eps 1e-3",
    );
}

#[test]
fn stage_2_the_sinkhorn_split_matches_the_reference() {
    let o = Oracle::load();
    let (streams, positions) = (o.usize_at("streams"), o.usize_at("positions"));
    let mix_rows = o.usize_at("mix_rows");
    let mixes = o.floats(&["stages", "mix_projection"]);
    let (scale, base) = (
        o.floats(&["weights", "hc_scale"]),
        o.floats(&["weights", "hc_base"]),
    );
    let (pre, post, comb) = (
        o.floats(&["stages", "sinkhorn_pre"]),
        o.floats(&["stages", "sinkhorn_post"]),
        o.floats(&["stages", "sinkhorn_comb"]),
    );

    assert_eq!(scale.len(), HC_SCALE_LEN);
    assert_eq!(mix_rows, mix_rows_for(streams));

    for p in 0..positions {
        let split = split_sinkhorn(chunk(&mixes, p, mix_rows), &scale, &base, o.topology());
        assert_close(&split.pre, chunk(&pre, p, streams), "sinkhorn pre");
        assert_close(&split.post, chunk(&post, p, streams), "sinkhorn post");
        assert_close(
            &split.comb,
            chunk(&comb, p, streams * streams),
            "sinkhorn comb",
        );
    }
}

/// Twenty iterations must not agree with one. If they did, the split
/// would be a reshape with extra steps and the fixture could not tell an
/// implementation that skipped the loop from one that ran it.
#[test]
fn stage_2_the_iteration_count_is_load_bearing() {
    let o = Oracle::load();
    let (streams, mix_rows) = (o.usize_at("streams"), o.usize_at("mix_rows"));
    let mixes = o.floats(&["stages", "mix_projection"]);
    let (scale, base) = (
        o.floats(&["weights", "hc_scale"]),
        o.floats(&["weights", "hc_base"]),
    );
    let twenty = o.floats(&["stages", "sinkhorn_comb"]);
    let one = o.floats(&["controls", "comb_one_iteration"]);

    assert!(
        max_abs_diff(&twenty, &one) > CONTROL_FLOOR,
        "the oracle's own 1-iteration control must differ from its 20-iteration result"
    );

    let mut single = o.topology();
    single.sinkhorn_iters = 1;
    let split = split_sinkhorn(chunk(&mixes, 0, mix_rows), &scale, &base, single);
    assert_close(
        &split.comb,
        chunk(&one, 0, streams * streams),
        "comb at one iteration",
    );
}

/// The split ends on a column normalisation, so every column sums to
/// one. This is the structural fact that fixes the expansion's index
/// order independently of the broadcast it was read from.
#[test]
fn stage_2_leaves_every_column_summing_to_one() {
    let o = Oracle::load();
    let (streams, positions) = (o.usize_at("streams"), o.usize_at("positions"));
    let mix_rows = o.usize_at("mix_rows");
    let mixes = o.floats(&["stages", "mix_projection"]);
    let (scale, base) = (
        o.floats(&["weights", "hc_scale"]),
        o.floats(&["weights", "hc_base"]),
    );

    for p in 0..positions {
        let split = split_sinkhorn(chunk(&mixes, p, mix_rows), &scale, &base, o.topology());
        for k in 0..streams {
            let column: f32 = (0..streams).map(|j| split.comb_at(streams, j, k)).sum();
            assert!(
                (column - 1.0).abs() < 1e-3,
                "column {k} at position {p} sums to {column}, not 1"
            );
        }
    }
}

#[test]
fn stage_3_the_reduction_collapses_the_bundle() {
    let o = Oracle::load();
    let (streams, hidden, positions) = (
        o.usize_at("streams"),
        o.usize_at("hidden"),
        o.usize_at("positions"),
    );
    let x = o.floats(&["input", "x"]);
    let pre = o.floats(&["stages", "sinkhorn_pre"]);
    let expected = o.floats(&["stages", "reduced"]);

    for p in 0..positions {
        let got = reduce_streams(
            chunk(&pre, p, streams),
            chunk(&x, p, streams * hidden),
            streams,
            hidden,
        );
        assert_eq!(got.len(), hidden, "the reduction returns ONE vector");
        assert_close(&got, chunk(&expected, p, hidden), "stream reduction");
    }
}

/// Stage four is an ordinary sublayer. The claim under test is the
/// interface — it receives `[hidden]`, not `[streams, hidden]` — which
/// is why no existing operator needs to change to run under this
/// topology.
#[test]
fn stage_4_the_branch_sees_one_vector_not_the_bundle() {
    let o = Oracle::load();
    let (hidden, positions) = (o.usize_at("hidden"), o.usize_at("positions"));
    let weight = o.floats(&["weights", "branch_weight"]);
    let reduced = o.floats(&["stages", "reduced"]);
    let expected = o.floats(&["stages", "branched"]);

    for p in 0..positions {
        let input = chunk(&reduced, p, hidden);
        assert_eq!(input.len(), hidden);
        let got = branch(input, &weight, hidden);
        assert_close(&got, chunk(&expected, p, hidden), "branch");
    }
}

#[test]
fn stage_5_the_expansion_scatters_back_across_the_bundle() {
    let o = Oracle::load();
    let (streams, hidden, positions) = (
        o.usize_at("streams"),
        o.usize_at("hidden"),
        o.usize_at("positions"),
    );
    let mix_rows = o.usize_at("mix_rows");
    let mixes = o.floats(&["stages", "mix_projection"]);
    let (scale, base) = (
        o.floats(&["weights", "hc_scale"]),
        o.floats(&["weights", "hc_base"]),
    );
    let (x, branched) = (o.floats(&["input", "x"]), o.floats(&["stages", "branched"]));
    let expected = o.floats(&["stages", "expanded"]);

    for p in 0..positions {
        let split = split_sinkhorn(chunk(&mixes, p, mix_rows), &scale, &base, o.topology());
        let got = expand_streams(
            chunk(&branched, p, hidden),
            chunk(&x, p, streams * hidden),
            &split,
            streams,
            hidden,
        );
        assert_eq!(
            got.len(),
            streams * hidden,
            "the expansion returns a bundle"
        );
        assert_close(
            &got,
            chunk(&expected, p, streams * hidden),
            "stream expansion",
        );
    }
}

/// `out[k] = post[k]*branch + Σ_j comb[j,k]*residual[j]`, not
/// `Σ_j comb[k,j]*residual[j]`. Both orders type-check and both produce
/// a plausible bundle, so the fixture has to be able to tell them apart
/// — this asserts that it can, then asserts which one the build computes.
#[test]
fn stage_5_reads_comb_in_the_reference_index_order() {
    let o = Oracle::load();
    let (streams, hidden) = (o.usize_at("streams"), o.usize_at("hidden"));
    let mix_rows = o.usize_at("mix_rows");
    let mixes = o.floats(&["stages", "mix_projection"]);
    let (scale, base) = (
        o.floats(&["weights", "hc_scale"]),
        o.floats(&["weights", "hc_base"]),
    );
    let (x, branched) = (o.floats(&["input", "x"]), o.floats(&["stages", "branched"]));
    let reference = o.floats(&["stages", "expanded"]);
    let transposed = o.floats(&["controls", "expanded_transposed_comb"]);

    assert!(
        max_abs_diff(&reference, &transposed) > CONTROL_FLOOR,
        "a fixture where the transposed order agrees cannot see index order at all"
    );

    let mut split = split_sinkhorn(chunk(&mixes, 0, mix_rows), &scale, &base, o.topology());
    let got = expand_streams(
        chunk(&branched, 0, hidden),
        chunk(&x, 0, streams * hidden),
        &split,
        streams,
        hidden,
    );
    assert_close(
        &got,
        chunk(&reference, 0, streams * hidden),
        "reference order",
    );

    // Transpose comb in place and confirm the build then computes the
    // control, which pins WHICH index the implementation is treating as
    // the destination.
    let original = split.comb.clone();
    for j in 0..streams {
        for k in 0..streams {
            split.comb[j * streams + k] = original[k * streams + j];
        }
    }
    let flipped = expand_streams(
        chunk(&branched, 0, hidden),
        chunk(&x, 0, streams * hidden),
        &split,
        streams,
        hidden,
    );
    assert_close(
        &flipped,
        chunk(&transposed, 0, streams * hidden),
        "transposed order",
    );
}

#[test]
fn the_five_stages_compose_into_the_reference_sublayer() {
    let o = Oracle::load();
    let (streams, hidden, positions) = (
        o.usize_at("streams"),
        o.usize_at("hidden"),
        o.usize_at("positions"),
    );
    let (x, weight) = (
        o.floats(&["input", "x"]),
        o.floats(&["weights", "branch_weight"]),
    );
    let (scale, base, hc_fn) = (
        o.floats(&["weights", "hc_scale"]),
        o.floats(&["weights", "hc_base"]),
        o.floats(&["weights", "hc_fn"]),
    );
    let expected = o.floats(&["stages", "expanded"]);
    let norm_eps = o.f64_at("norm_eps");

    let site = SiteWeights {
        mix_fn: &hc_fn,
        base: &base,
        scale: &scale,
    };
    for p in 0..positions {
        let got = sublayer_forward(
            chunk(&x, p, streams * hidden),
            streams,
            hidden,
            &site,
            o.topology(),
            norm_eps,
            |v| branch(v, &weight, hidden),
        );
        assert_close(
            &got,
            chunk(&expected, p, streams * hidden),
            "composed sublayer",
        );
    }
}

/// The whole point of the topology: it is not `h + f(h)`. The oracle
/// carries a single-stream reading of the same layer and it must
/// disagree — otherwise the fixture would not distinguish the two
/// programmes, and wave 16's refusal would have been protecting nothing.
#[test]
fn the_topology_does_not_agree_with_an_ordinary_residual() {
    let o = Oracle::load();
    let (streams, hidden, positions) = (
        o.usize_at("streams"),
        o.usize_at("hidden"),
        o.usize_at("positions"),
    );
    let expanded = o.floats(&["stages", "expanded"]);
    let single = o.floats(&["controls", "single_stream_residual"]);

    for p in 0..positions {
        let bundle = chunk(&expanded, p, streams * hidden);
        let plain = chunk(&single, p, hidden);
        for k in 0..streams {
            let stream = &bundle[k * hidden..(k + 1) * hidden];
            assert!(
                max_abs_diff(stream, plain) > CONTROL_FLOOR,
                "stream {k} at position {p} coincides with h + f(h); the fixture proves nothing"
            );
        }
    }
}

/// The head runs NO split: no iterations, no post, no combination
/// matrix, a `[streams, streams*hidden]` projection and a scalar scale.
#[test]
fn the_head_reduction_is_its_own_operation() {
    let o = Oracle::load();
    let (streams, hidden, positions) = (
        o.usize_at("streams"),
        o.usize_at("hidden"),
        o.usize_at("positions"),
    );
    let x = o.floats(&["input", "x"]);
    let (head_fn, head_base) = (
        o.floats(&["weights", "head_fn"]),
        o.floats(&["weights", "head_base"]),
    );
    let head_scale = o.doc["weights"]["head_scale"].as_f64().expect("scalar") as f32;
    let expected = o.floats(&["head", "reduced"]);

    assert_eq!(
        head_fn.len(),
        streams * streams * hidden,
        "the head's projection has ONE row per stream, not (2 + streams) * streams"
    );

    for p in 0..positions {
        let head = HeadWeights {
            reduce_fn: &head_fn,
            base: &head_base,
            scale: head_scale,
        };
        let got = head_reduce(
            chunk(&x, p, streams * hidden),
            streams,
            hidden,
            &head,
            o.f64_at("norm_eps"),
            o.f64_at("hc_eps"),
        );
        assert_close(&got, chunk(&expected, p, hidden), "head reduction");
    }
}

/// The embedding is REPLICATED into every stream — not zero-padded, not
/// split, not learned.
#[test]
fn the_embedding_replicates_into_every_stream() {
    let hidden_state = [0.5f32, -1.25, 3.0];
    let streams = 4;
    let bundle = expand_embedding(&hidden_state, streams);

    assert_eq!(bundle.len(), streams * hidden_state.len());
    for k in 0..streams {
        assert_eq!(
            &bundle[k * hidden_state.len()..(k + 1) * hidden_state.len()],
            &hidden_state,
            "stream {k} must be a copy of the embedding"
        );
    }
}

/// `pre` carries `+ eps` and `post` does not. At the checkpoint's own
/// `hc_eps` of 1e-6 that asymmetry is smaller than f32 transcription
/// noise, so no comparison against the oracle can see it — dropping the
/// term passes every numeric assertion above. This isolates the
/// STRUCTURE instead: run the split at two very different epsilons and
/// assert `pre` moves by exactly the difference while `post` does not
/// move at all.
///
/// Found by mutation: removing the term left the suite green.
#[test]
fn stage_2_adds_eps_to_pre_and_not_to_post() {
    let o = Oracle::load();
    let mix_rows = o.usize_at("mix_rows");
    let mixes = o.floats(&["stages", "mix_projection"]);
    let (scale, base) = (
        o.floats(&["weights", "hc_scale"]),
        o.floats(&["weights", "hc_base"]),
    );

    // Far apart, and far above f32 noise, so the difference is legible.
    const SMALL_EPS: f64 = 1e-3;
    const LARGE_EPS: f64 = 0.25;

    let at = |eps: f64| {
        let mut topology = o.topology();
        topology.sinkhorn_eps = eps;
        split_sinkhorn(chunk(&mixes, 0, mix_rows), &scale, &base, topology)
    };
    let (small, large) = (at(SMALL_EPS), at(LARGE_EPS));
    let shift = (LARGE_EPS - SMALL_EPS) as f32;

    for (j, (lo, hi)) in small.pre.iter().zip(&large.pre).enumerate() {
        assert!(
            ((hi - lo) - shift).abs() < TOLERANCE,
            "pre[{j}] must shift by exactly the epsilon difference: {lo} -> {hi}"
        );
    }
    for (j, (lo, hi)) in small.post.iter().zip(&large.post).enumerate() {
        assert!(
            (hi - lo).abs() < TOLERANCE,
            "post[{j}] must NOT carry epsilon: {lo} -> {hi}"
        );
    }
}

/// At the checkpoint's twenty iterations the split has CONVERGED: the
/// matrix is doubly stochastic, rows and columns both summing to one.
///
/// This is why the row/column order inside the loop is not observable at
/// twenty — measured at 9e-8, below f32 noise — while the iteration
/// COUNT plainly is. Stating the convergence positively is honest where
/// a silent gap would not be: swapping the two passes is an equivalent
/// mutation here, not an undetected defect, and
/// [`stage_2_pins_the_pass_order_where_it_is_still_observable`] covers
/// the regime where it is not equivalent.
#[test]
fn stage_2_converges_to_a_doubly_stochastic_matrix() {
    let o = Oracle::load();
    let (streams, positions) = (o.usize_at("streams"), o.usize_at("positions"));
    let mix_rows = o.usize_at("mix_rows");
    let mixes = o.floats(&["stages", "mix_projection"]);
    let (scale, base) = (
        o.floats(&["weights", "hc_scale"]),
        o.floats(&["weights", "hc_base"]),
    );

    /// Convergence slack at twenty iterations, measured at ~1e-6.
    const DOUBLY_STOCHASTIC_SLACK: f32 = 1e-3;

    for p in 0..positions {
        let split = split_sinkhorn(chunk(&mixes, p, mix_rows), &scale, &base, o.topology());
        for i in 0..streams {
            let row: f32 = (0..streams).map(|k| split.comb_at(streams, i, k)).sum();
            let column: f32 = (0..streams).map(|j| split.comb_at(streams, j, i)).sum();
            assert!(
                (row - 1.0).abs() < DOUBLY_STOCHASTIC_SLACK,
                "row {i} at position {p} sums to {row}"
            );
            assert!(
                (column - 1.0).abs() < DOUBLY_STOCHASTIC_SLACK,
                "column {i} at position {p} sums to {column}"
            );
        }
    }
}

/// The reference normalises rows THEN columns inside the loop. At twenty
/// iterations that is unobservable (the matrix has converged), so this
/// pins it at two, where the two orders differ by 9e-2.
///
/// Found by mutation: swapping the passes left the whole suite green,
/// and the two-iteration golden is what makes the order a tested claim
/// rather than an accident of convergence.
#[test]
fn stage_2_pins_the_pass_order_where_it_is_still_observable() {
    let o = Oracle::load();
    let (streams, mix_rows) = (o.usize_at("streams"), o.usize_at("mix_rows"));
    let mixes = o.floats(&["stages", "mix_projection"]);
    let (scale, base) = (
        o.floats(&["weights", "hc_scale"]),
        o.floats(&["weights", "hc_base"]),
    );
    let converged = o.floats(&["stages", "sinkhorn_comb"]);
    let two = o.floats(&["controls", "comb_two_iterations"]);

    assert!(
        max_abs_diff(&converged, &two) > CONTROL_FLOOR,
        "two iterations must not already be converged, or this pins nothing"
    );

    let mut topology = o.topology();
    topology.sinkhorn_iters = 2;
    for p in 0..o.usize_at("positions") {
        let split = split_sinkhorn(chunk(&mixes, p, mix_rows), &scale, &base, topology);
        assert_close(
            &split.comb,
            chunk(&two, p, streams * streams),
            "comb at two iterations",
        );
    }
}
