#!/usr/bin/env python3
"""Generate/check checkout facts; export with provenance for downstream sites.

Python 3.11+, no dependencies or network. Numeric authorities are Rust constants;
command names are the simple Clap enums, independently checked by binary tests.
This records source/package identity, never claims a published release or main.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import tomllib

ROOT = Path(__file__).resolve().parent.parent
GENERATED = ROOT / "docs/generated"
SOURCES = {
    "package": "crates/vindex-cli/Cargo.toml",
    "generation": "crates/larql-vindex/src/format/generation.rs",
    "graph": "crates/larql-vindex/src/format/vindex3/graph/mod.rs",
    "plan": "crates/larql-vindex/src/format/vindex3/plan/report.rs",
    "spec": "crates/larql-vindex/docs/vindex3-format-spec.md",
    "vindex": "crates/vindex-cli/src/main.rs",
    "larql_vindex3": "crates/larql-cli/src/commands/primary/vindex3_cmd/mod.rs",
}


def one(pattern: str, text: str) -> str:
    matches = re.findall(pattern, text, re.MULTILINE)
    if len(matches) != 1:
        raise ValueError(f"expected one authority for {pattern!r}, found {len(matches)}")
    return matches[0]


def command_names(source: str, enum: str) -> list[str]:
    # Intentionally narrow. Refuse custom Clap names/flattening/cfg rather than
    # silently inventing a command tree. The compiled Clap tests are authoritative.
    body = one(r"^(?:pub )?enum " + enum + r" \{\n([\s\S]*?)^\}", source)
    if re.search(r"#\[(?:command|cfg|clap)", body):
        raise ValueError(f"{enum}: custom command attributes need generator support")
    variants = re.findall(r"^    ([A-Z][A-Za-z0-9]*)(?:\s*\{|\(|,)", body, re.MULTILINE)
    if not variants:
        raise ValueError(f"{enum}: empty command inventory")
    return sorted(re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower() for name in variants)


def facts() -> dict:
    source = {key: (ROOT / path).read_text() for key, path in SOURCES.items()}
    constants = {}
    for key, names in {
        "generation": ["V3_CURRENT_SCHEMA"],
        "graph": ["GRAPH_SCHEMA"],
        "plan": ["PLAN_SCHEMA", "PLANNER_SEMANTICS_VERSION"],
    }.items():
        for name in names:
            constants[name] = int(one(r"^pub const " + name + r": u32 = (\d+);$", source[key]))
    constants["DEFAULT_EXTRACTION_GENERATION"] = one(
        r"^pub const DEFAULT_EXTRACTION_GENERATION: ContainerGeneration = ContainerGeneration::(V\d+);$",
        source["generation"],
    )
    return {
        "facts_schema": 1,
        "scope": "source-checkout",
        "vindex_cli_version": tomllib.loads(source["package"])["package"]["version"],
        "spec_version": one(r"^\*\*Version:\*\* (\S+)$", source["spec"]),
        "constants": constants,
        "commands": {
            "vindex": command_names(source["vindex"], "Command"),
            "larql_vindex3": command_names(source["larql_vindex3"], "Vindex3Command"),
        },
        "sources": SOURCES,
    }


def markdown(data: dict) -> str:
    rows = {
        "vindex package version (not release availability)": data["vindex_cli_version"],
        "Candidate specification version": data["spec_version"],
        **data["constants"],
    }
    text = (
        "# Current VINDEX3 facts\n\n"
        "**Class: CURRENT — generated.** Run `python3 scripts/current_facts.py --write` "
        "from the repository root; CI runs `--check`. Do not edit this file.\n\n"
        "These describe the source checkout, not the latest published binary. "
        "[Documentation policy](../documentation-policy.md) defines the authority boundary. "
        "[Machine-readable facts](current-facts.json) contain the source paths.\n\n"
        "| Fact | Value |\n|---|---|\n"
    )
    text += "".join(f"| {name} | `{value}` |\n" for name, value in rows.items())
    for command, names in data["commands"].items():
        text += f"\n## {command.replace('_', ' ')} commands\n\n"
        text += ", ".join(f"`{name}`" for name in names) + ".\n"
    text += (
        "\nInventories list explicit top-level subcommands; Clap's generated help command, "
        "flags and aliases are excluded. Binary unit tests compare these lists with "
        "the actual Clap command trees. Use each command's `--help` for arguments.\n\n"
        "To export for a site, run `python3 scripts/current_facts.py --export /tmp/vindex3-facts.json`. "
        "The export adds the checkout commit, dirty flag and SHA-256 of each authority file. "
        "A consumer must retain that provenance and label dirty exports as local work. "
        "CI publishes a clean-checkout export as an artifact; no reference SHA is hand-maintained here.\n"
    )
    return text


def git(*args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True).strip()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--export", type=Path)
    args = parser.parse_args()
    data = facts()
    outputs = {
        GENERATED / "current-facts.json": json.dumps(data, indent=2) + "\n",
        GENERATED / "current-facts.md": markdown(data),
    }
    if args.export:
        # Read status before creating the output; generated outputs are already
        # checked in CI. An export does not establish release or branch identity.
        data["provenance"] = {
            "git_commit": git("rev-parse", "HEAD"),
            "dirty": bool(git("status", "--porcelain", "--untracked-files=normal")),
            "source_sha256": {
                path: hashlib.sha256((ROOT / path).read_bytes()).hexdigest()
                for path in SOURCES.values()
            },
        }
        args.export.write_text(json.dumps(data, indent=2) + "\n")
        return 0
    if args.write:
        GENERATED.mkdir(parents=True, exist_ok=True)
        for path, content in outputs.items():
            path.write_text(content)
        return 0
    stale = [str(path.relative_to(ROOT)) for path, content in outputs.items()
             if not path.exists() or path.read_text() != content]
    if stale:
        print("Stale facts: " + ", ".join(stale) + "; run python3 scripts/current_facts.py --write", file=sys.stderr)
        return 1
    print("Current facts match source authorities.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
