#!/usr/bin/env python3
"""Generate the FOREIGN-encoded fixture for the BF16_ZLIB codec.

The codec's lossless claim must be proved against a stream produced by an
implementation it does not share code with. Python's `zlib` module is
that implementation: a different inflater/deflater lineage from the
crate the codec decodes with, so a decode that matches here is a
statement about the WIRE FORMAT (RFC 1950 framing over RFC 1951
DEFLATE), not about one library agreeing with itself.

Two images, each written as its bf16 code units and as the zlib stream
Python produced for the little-endian byte image of those units:

* `[7, 37]` — an AWKWARD shape (odd rows, odd k, 259 elements, 518 raw
  bytes) whose rows make the stream COMPRESS below the raw size: row 0
  and row 3 are identical, row 1 is all zeros, rows 2/4/5 are noise, and
  row 6 carries every bf16 special value (-0.0, +0.0, the smallest
  subnormal, the largest finite, both infinities, a quiet NaN with a
  non-zero payload and its negative) so losslessness is judged at the
  bit level, not through float equality.
* `[3, 256]` — pure noise, so the stream EXPANDS past the raw 1536
  bytes. Together the two images witness that the stored size of this
  representation is not a function of its shape in either direction.

Deterministic: every value comes from the LCG below, so re-running this
script reproduces the file byte for byte. The output is `#[rustfmt::skip]`
so `cargo fmt --check` judges the generator, not the arrays.

Usage:
    python3 scripts/gen_bf16_zlib_fixture.py
"""
from __future__ import annotations

import platform
import struct
import sys
import zlib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = (
    REPO
    / "crates/larql-vindex/src/format/vindex3/represent/codec/tests/fixtures"
    / "bf16_zlib_foreign.rs"
)

LEVEL = 9

# bf16 exponent field, all ones = inf/NaN. Noise rows stay FINITE so the
# special-value row is the only place non-finite units appear, which is
# what lets a test assert that they survived rather than merely that the
# stream round-tripped.
EXP_MASK = 0x7F80

SPECIALS = [
    0x8000,  # -0.0
    0x0000,  # +0.0
    0x0001,  # smallest positive subnormal
    0x7F7F,  # largest finite
    0x7F80,  # +inf
    0xFF80,  # -inf
    0x7FC1,  # quiet NaN, payload 1
    0xFFC1,  # negative quiet NaN, payload 1
]


class Lcg:
    """A 64-bit LCG; the same constants `fixtures::lcg_values` uses."""

    def __init__(self, seed: int) -> None:
        self.state = seed

    def next_u16(self) -> int:
        self.state = (self.state * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        return (self.state >> 48) & 0xFFFF


def finite_noise(lcg: Lcg, n: int) -> list[int]:
    out = []
    for _ in range(n):
        v = lcg.next_u16()
        if v & EXP_MASK == EXP_MASK:
            v ^= 0x0080  # drop the exponent out of the inf/NaN band
        out.append(v)
    return out


def awkward_image() -> tuple[list[int], list[int]]:
    rows, k = 7, 37
    lcg = Lcg(0x5EED_BF16)
    row0 = finite_noise(lcg, k)
    rows_units = [
        row0,
        [0] * k,
        finite_noise(lcg, k),
        list(row0),
        finite_noise(lcg, k),
        finite_noise(lcg, k),
        SPECIALS + finite_noise(lcg, k - len(SPECIALS)),
    ]
    units = [u for row in rows_units for u in row]
    assert len(units) == rows * k
    return [rows, k], units


def noise_image() -> tuple[list[int], list[int]]:
    rows, k = 3, 256
    return [rows, k], finite_noise(Lcg(0x0DD_C0DE5), rows * k)


def le_bytes(units: list[int]) -> bytes:
    return b"".join(struct.pack("<H", u) for u in units)


def rust_array(name: str, ty: str, values: list[int], per_line: int, fmt: str) -> str:
    lines = []
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        lines.append("    " + ", ".join(fmt % v for v in chunk) + ",")
    body = "\n".join(lines)
    return f"#[rustfmt::skip]\npub const {name}: [{ty}; {len(values)}] = [\n{body}\n];\n"


def main() -> None:
    awk_shape, awk_units = awkward_image()
    noise_shape, noise_units = noise_image()
    awk_stream = zlib.compress(le_bytes(awk_units), LEVEL)
    noise_stream = zlib.compress(le_bytes(noise_units), LEVEL)
    awk_raw = 2 * len(awk_units)
    noise_raw = 2 * len(noise_units)
    assert len(awk_stream) < awk_raw, "the awkward image must compress"
    assert len(noise_stream) > noise_raw, "the noise image must expand"

    header = f"""//! Generated by `scripts/gen_bf16_zlib_fixture.py`. Do not hand-edit.
//!
//! A FOREIGN encoder's streams for the `BF16_ZLIB` codec: produced by
//! Python {platform.python_version()} `zlib` (zlib {zlib.ZLIB_VERSION}) at level {LEVEL},
//! not by the crate the codec inflates with. A bit-exact decode of these
//! is a statement about RFC 1950 / RFC 1951, not about one library
//! agreeing with itself.
//!
//! Sizes, which are the point: the `[7, 37]` image is {awk_raw} raw bytes
//! and {len(awk_stream)} coded; the `[3, 256]` noise image is {noise_raw} raw bytes
//! and {len(noise_stream)} coded. Same codec, opposite directions — stored size
//! is a property of the instance.

/// The awkward image's shape: odd rows, odd k, 259 elements.
pub const AWKWARD_SHAPE: [usize; 2] = [{awk_shape[0]}, {awk_shape[1]}];
/// Row 3 repeats row 0 and row 1 is zeros, so the image compresses.
pub const AWKWARD_REPEATED_ROWS: (usize, usize) = (0, 3);
pub const AWKWARD_ZERO_ROW: usize = 1;
/// The row carrying every bf16 special value, specials first.
pub const AWKWARD_SPECIAL_ROW: usize = 6;
pub const SPECIALS: [u16; {len(SPECIALS)}] = [{", ".join("0x%04X" % s for s in SPECIALS)}];

/// The noise image's shape.
pub const NOISE_SHAPE: [usize; 2] = [{noise_shape[0]}, {noise_shape[1]}];

"""
    body = (
        rust_array("AWKWARD_UNITS", "u16", awk_units, 8, "0x%04X")
        + "\n"
        + rust_array("AWKWARD_STREAM", "u8", list(awk_stream), 12, "0x%02X")
        + "\n"
        + rust_array("NOISE_UNITS", "u16", noise_units, 8, "0x%04X")
        + "\n"
        + rust_array("NOISE_STREAM", "u8", list(noise_stream), 12, "0x%02X")
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + body)
    print(
        f"wrote {OUT.relative_to(REPO)}: awkward {awk_raw}->{len(awk_stream)} B, "
        f"noise {noise_raw}->{len(noise_stream)} B",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
