#!/usr/bin/env python3
"""Generate the tiny, COMMITTED `kda_oracle.json` fixture for
`exec::kda`'s own parity test.

P4c-4 regenerates this: `q_proj`/`k_proj`/`v_proj`/`o_proj` are now BF16 in
the executor (`KdaWeights`'s four widest operands, routed through the
row-parallel `FusedBf16` path — see `exec/kda.rs::matvec_bf16`), so the
oracle must compute from the SAME bf16-exact bits the Rust side reads,
not from arbitrary-precision f32 randoms. Everything else — convolution,
gates, recurrence, gated norm — stays plain f32, unchanged from the
fixture this replaces.

Same reasoning `kimi_mla_oracle_export.py` already used for MLA: the
arithmetic is identical at any width, small enough to commit is small
enough to actually get run, and Kimi's real geometry (32 heads x 128) is
its own separate env-gated real-weight gate
(`kimi_kda_layer_export.py`/`kimi_kda_layer_real.rs`,
`kimi_stack_export.py`/`stack_real.rs`) — proving indexing and stride at
scale, not the formula.

    python scripts/kda_oracle_export.py > \
        crates/larql-vindex/src/format/vindex3/opplan/exec/tests/kda_oracle.json
"""

from __future__ import annotations

import json

import torch

import kda_reference as ref

SEED = 20260827

#: Same geometry the fixture this replaces used — 2 heads x 4, hidden 6,
#: conv kernel 4 — kept for continuity; nothing about it is load-bearing,
#: `kda_parity.rs` reads geometry from the JSON rather than assuming it.
NUM_HEADS = 2
HEAD_DIM = 4
HIDDEN = 6
CONV_KERNEL = 4

#: The longest run; N=1 and N=2 take a causal prefix of this same
#: sequence, so a state-carry defect that only shows up past N=1 is not
#: hiding behind a differently-seeded shorter input.
MAX_POSITIONS = 8


def bf16_exact(t: torch.Tensor) -> torch.Tensor:
    """Round-trip through bf16 so Python computes from the SAME bits the
    Rust side reads back from a bf16 code unit — truncation is lossless
    only when the f32 value already has zero in its low 16 mantissa
    bits, which a real bf16-native checkpoint tensor has by construction
    and an arbitrary f32 random does not."""
    return t.detach().to(torch.bfloat16).to(torch.float32)


def lst(t: torch.Tensor) -> list:
    return [round(v, 8) for v in t.detach().flatten().tolist()]


def main() -> int:
    torch.manual_seed(SEED)
    H, D, hidden, K = NUM_HEADS, HEAD_DIM, HIDDEN, CONV_KERNEL

    w = ref.KdaWeights(
        q_proj=bf16_exact(torch.randn(H * D, hidden) * 0.3),
        k_proj=bf16_exact(torch.randn(H * D, hidden) * 0.3),
        v_proj=bf16_exact(torch.randn(H * D, hidden) * 0.3),
        q_conv1d=torch.randn(H * D, 1, K) * 0.3,
        k_conv1d=torch.randn(H * D, 1, K) * 0.3,
        v_conv1d=torch.randn(H * D, 1, K) * 0.3,
        f_a_proj=torch.randn(D, hidden) * 0.3,
        f_b_proj=torch.randn(H * D, D) * 0.3,
        g_a_proj=torch.randn(D, hidden) * 0.3,
        g_b_proj=torch.randn(H * D, D) * 0.3,
        b_proj=torch.randn(H, hidden) * 0.3,
        a_log=torch.rand(H) * 0.5,  # kept small: exp(A_log) scales the decay
        dt_bias=torch.randn(H * D) * 0.2,
        o_norm=torch.rand(D) * 0.5 + 0.75,  # near 1.0, never zero
        o_proj=bf16_exact(torch.randn(hidden, H * D) * 0.3),
    )
    x_full = torch.randn(MAX_POSITIONS, hidden) * 0.2

    weights = {name: lst(getattr(w, name)) for name in ref.KdaWeights.__dataclass_fields__}

    runs = {}
    for n in (1, 2, 8):
        x_n = x_full[:n]
        result = ref.kda_forward(x_n, w)
        runs[str(n)] = {
            "input": lst(x_n),
            "boundaries": {name: lst(result[name]) for name in ref.BOUNDARIES},
            "state": lst(result["_state"]),
            "conv_state": [lst(s) for s in result["_conv_state"]],
        }

    fixture = {
        "_comment": (
            "Tiny KDA layer + oracle outputs. Generated by "
            "scripts/kda_oracle_export.py; q/k/v/o_proj are BF16-exact "
            "(P4c-4), everything else f32. See docs/glm5-flash-funnel.md "
            "4.15 for the operator's own provenance."
        ),
        "num_heads": H,
        "head_dim": D,
        "hidden": hidden,
        "conv_kernel": K,
        "rms_eps": ref.RMS_EPS,
        "seed": SEED,
        "weights": weights,
        "runs": runs,
    }
    print(json.dumps(fixture, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
